package com.trainerclienthub.model;

/**
 * Categories of reports that can be generated by an admin trainer.
 * Mirrors the ENUM constraint on the {@code report} database table.
 */
public enum ReportType {
    CLIENT,
    MEMBERSHIP,
    TRAINER,
    ATTENDANCE,
    REVENUE
}
